import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

SOURCES=['awtk_cpp.cpp', 'assets.c']
env.Library(os.path.join(LIB_DIR, 'awtk-cpp'), SOURCES)





