import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];

SOURCES=['awtk_cpp.cpp', Glob('assets*.c'), Glob('*.cpp')]
env.Library(os.path.join(LIB_DIR, 'awtk-cpp'), SOURCES)





